"""Generate the compliance matrix and the document register.

The matrix answers one question per requirement: *which document will show
compliance, with which method, and in what state is it today*. It is generated
from ``model/compliance.yaml`` (the document register and the change
classification) and from the evidence register, so it cannot be written to say
something the model does not.

``python -m tools.compliance`` writes ``docs/compliance-matrix.md``;
``python -m tools.compliance --check`` fails when the committed file differs from
the model, which is how CI keeps it current.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from .model import Model, REPO_ROOT, load_model

DOC_PATH = Path("docs/compliance-matrix.md")

HEADER = (
    "<!-- Generated by tools/compliance.py — do not edit by hand. -->\n"
    "<!-- Run: python -m tools.compliance -->\n"
)


def _document_of(model: Model, requirement_uid: str) -> str:
    owners = [document.id for document in model.documents if requirement_uid in document.covers]
    return ", ".join(owners) if owners else "—"


def _document_status(model: Model, requirement_uid: str) -> str:
    owners = [
        document.status for document in model.documents if requirement_uid in document.covers
    ]
    return ", ".join(owners) if owners else "—"


def render_compliance(model: Model) -> str:
    """Render the compliance matrix as Markdown."""
    lines: list[str] = [HEADER, "", "# Compliance matrix", ""]
    lines.append(
        "Every requirement of the study, the document that will show compliance, the method "
        "behind it and the state of the evidence today. Generated from the model: the document "
        "register and the change classification live in `model/compliance.yaml`."
    )
    lines.append("")

    classification = model.classification
    lines.append("## Change classification")
    lines.append("")
    if classification is None:
        lines.append("No change classification recorded.")
        lines.append("")
    else:
        lines.append(
            f"**Status**: {classification.status} — **proposed**: {classification.proposed}"
        )
        lines.append("")
        lines.append(f"- **Basis**: {classification.basis}")
        lines.append(f"- **Approval route**: {classification.approval_route}")
        lines.append(f"- **Privileges**: {classification.privileges}")
        lines.append("")
        lines.append("| Criterion | Appreciable effect | Why |")
        lines.append("| --- | --- | --- |")
        for criterion in classification.criteria:
            lines.append(
                f"| {criterion.criterion} | {criterion.effect} | {criterion.rationale} |"
            )
        lines.append("")
        if classification.open_items:
            lines.append("**Open items**")
            lines.append("")
            for item in classification.open_items:
                lines.append(f"- {item}")
            lines.append("")

    lines.append("## Requirements")
    lines.append("")
    lines.append(
        "| Requirement | Title | Source | Verification | Method | Document | Document state | "
        "Evidence |"
    )
    lines.append("| --- | --- | --- | --- | --- | --- | --- | --- |")
    for uid in sorted(model.requirements):
        requirement = model.requirements[uid]
        cases = model.verifications_of(uid)
        records = [model.evidence_of(case.uid) for case in cases]
        records = [record for record in records if record is not None]
        case_ids = ", ".join(case.uid for case in cases) or "—"
        methods = ", ".join(dict.fromkeys(record.method for record in records)) or "—"
        statuses = ", ".join(dict.fromkeys(record.status for record in records)) or "—"
        lines.append(
            f"| {uid} | {requirement.header} | {requirement.ref} | {case_ids} | {methods} | "
            f"{_document_of(model, uid)} | {_document_status(model, uid)} | {statuses} |"
        )
    lines.append("")

    lines.append("## Document register")
    lines.append("")
    lines.append("| Document | Title | Type | State | Path | Ticket | Requirements |")
    lines.append("| --- | --- | --- | --- | --- | --- | --- |")
    for document in model.documents:
        path = f"`{document.path}`" if document.path else "—"
        plan = document.plan or "—"
        lines.append(
            f"| {document.id} | {document.title} | {document.type} | {document.status} | {path} | "
            f"{plan} | {', '.join(document.covers)} |"
        )
    lines.append("")

    lines.append("## Instructions for continued airworthiness")
    lines.append("")
    lines.append(
        "The outline of the instructions for continued airworthiness is in `docs/ica.md`; it "
        "covers the installation, the payload replacement procedure, the scheduled inspections, "
        "the wear items and the parts list. Intervals and wear limits come with the platform "
        "maintenance programme and are still open."
    )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="tools.compliance", description=__doc__)
    parser.add_argument("--root", default=str(REPO_ROOT), help="repository root (default: the repo)")
    parser.add_argument("--check", action="store_true", help="fail if the document is out of date")
    args = parser.parse_args(argv)

    root = Path(args.root)
    content = render_compliance(load_model(root))
    target = root / DOC_PATH
    if args.check:
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current != content:
            print(f"{DOC_PATH} is out of date: run python -m tools.compliance")
            return 1
        print(f"{DOC_PATH} is up to date")
        return 0
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    print(f"wrote {DOC_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
