"""Generate the architecture document from the model.

The diagram and the allocation tables in ``docs/architecture.md`` are rendered
from ``model/architecture/architecture.yaml`` and the Doorstop requirement
documents: nothing in that file is drawn or typed by hand, and CI fails when the
committed file differs from the model.

Mermaid node identifiers cannot contain a hyphen, so the identifiers are the
element ids with the hyphens removed and the labels carry the real id.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from .model import REPO_ROOT, Model, load_model

DOC_PATH = Path("docs/architecture.md")

HEADER = (
    "<!-- Generated by tools/diagram.py — do not edit by hand. -->\n"
    "<!-- Run: python -m tools.diagram -->\n"
)

EXTERNAL_LABELS = {
    "EXT-PLATFORM": "Platform structure",
    "EXT-PAYLOAD": "EO/IR payload",
    "EXT-PLATFORM-BUS": "Platform 28 VDC bus",
    "EXT-MISSION-SYSTEM": "Mission system",
    "EXT-MAINTAINER": "Maintenance crew",
    "EXT-ENVIRONMENT": "Environment",
}


def node_id(element_id: str) -> str:
    """Return a Mermaid-safe node identifier for an element id."""
    return element_id.replace("-", "_").replace(".", "_")


def _requirement_list(ids: tuple[str, ...]) -> str:
    return "<br/>".join(ids) if ids else "—"


def render_architecture(model: Model) -> str:
    """Render the architecture document as Markdown with a Mermaid diagram."""
    lines: list[str] = [HEADER, "", "# Architecture", ""]
    lines.append(
        "Generated from the architecture model and the requirements: the functions, the "
        "components that realise them, the interfaces and the external boundary."
    )
    lines.append("")

    lines.append("## Diagram")
    lines.append("")
    lines.append("```mermaid")
    lines.append("graph LR")
    for external in model.externals:
        label = EXTERNAL_LABELS.get(external, external)
        lines.append(f'    {node_id(external)}(["{label}"])')
    for component in model.components:
        count = len(component.requirements)
        plural = "requirement" if count == 1 else "requirements"
        lines.append(f'    {node_id(component.id)}["{component.id}<br/>{component.name}<br/>{count} {plural}"]')
    for interface in model.interfaces:
        lines.append(
            f'    {node_id(interface.source)} -->|"{interface.id}: {interface.name}"| '
            f"{node_id(interface.target)}"
        )
    lines.append("")
    for component in model.components:
        lines.append(f"    class {node_id(component.id)} component")
    if model.components:
        lines.append("    classDef component fill:#eef,stroke:#446")
    lines.append("```")
    lines.append("")

    lines.append("## Functions")
    lines.append("")
    lines.append("| Function | Name | Requirements | Realised by |")
    lines.append("| --- | --- | --- | --- |")
    for function in model.functions:
        realised_by = ", ".join(
            component.id for component in model.components if function.id in component.realizes
        )
        lines.append(
            f"| {function.id} | {function.name} | {_requirement_list(function.requirements)} | "
            f"{realised_by or '—'} |"
        )
    lines.append("")

    lines.append("## Components")
    lines.append("")
    lines.append("| Component | Name | Realises | Requirements |")
    lines.append("| --- | --- | --- | --- |")
    for component in model.components:
        lines.append(
            f"| {component.id} | {component.name} | {', '.join(component.realizes) or '—'} | "
            f"{_requirement_list(component.requirements)} |"
        )
    lines.append("")

    lines.append("## Interfaces")
    lines.append("")
    lines.append("| Interface | Name | From | To | Requirements |")
    lines.append("| --- | --- | --- | --- | --- |")
    for interface in model.interfaces:
        lines.append(
            f"| {interface.id} | {interface.name} | {interface.source} | {interface.target} | "
            f"{_requirement_list(interface.requirements)} |"
        )
    lines.append("")

    lines.append("## External boundary")
    lines.append("")
    lines.append("| External | Meaning |")
    lines.append("| --- | --- |")
    for external in model.externals:
        lines.append(f"| {external} | {EXTERNAL_LABELS.get(external, '—')} |")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="tools.diagram", description=__doc__)
    parser.add_argument("--root", default=str(REPO_ROOT), help="repository root (default: the repo)")
    parser.add_argument("--check", action="store_true", help="fail if the document is out of date")
    args = parser.parse_args(argv)

    root = Path(args.root)
    content = render_architecture(load_model(root))
    target = root / DOC_PATH
    if args.check:
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current != content:
            print(f"{DOC_PATH} is out of date: run python -m tools.diagram")
            return 1
        print(f"{DOC_PATH} is up to date")
        return 0
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    print(f"wrote {DOC_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
