"""Command line interface to the model.

Usage::

    python -m tools.traceability check            # validate, exit 1 on error
    python -m tools.traceability report           # write docs/traceability.md
    python -m tools.traceability report --check   # fail if the report is stale

``check`` is the gate used in CI and in ``pytest``: a broken link, an
unallocated requirement or an evidence claim without its artifact fails here.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from .model import REPO_ROOT, Model, load_model
from .rules import Finding, check_model

REPORT_PATH = Path("docs/traceability.md")

REPORT_HEADER = (
    "<!-- Generated by tools/traceability.py — do not edit by hand. -->\n"
    "<!-- Run: python -m tools.traceability report -->\n"
)


def render_report(model: Model) -> str:
    """Render the traceability matrix as Markdown."""
    lines: list[str] = [REPORT_HEADER, ""]
    lines.append("# Traceability matrix")
    lines.append("")
    lines.append(
        "Every requirement of the installation kit, the architecture element that "
        "owns it, the verification case that closes it and the state of the "
        "evidence. Generated from the model, never written by hand."
    )
    lines.append("")

    statuses = [record.status for record in model.evidence.values()]
    lines.append("## Summary")
    lines.append("")
    lines.append("| Item | Count |")
    lines.append("| --- | --- |")
    lines.append(f"| System requirements | {len(model.requirements)} |")
    lines.append(f"| Verification cases | {len(model.verifications)} |")
    lines.append(f"| Functions | {len(model.functions)} |")
    lines.append(f"| Components | {len(model.components)} |")
    lines.append(f"| Interfaces | {len(model.interfaces)} |")
    lines.append(f"| Declared assumptions | {len(model.assumptions)} |")
    lines.append("")
    lines.append("| Evidence status | Count |")
    lines.append("| --- | --- |")
    for status in ("PASS", "WARN", "FAIL", "LIMITATION", "BLOCKED", "FUTURE"):
        lines.append(f"| {status} | {statuses.count(status)} |")
    lines.append("")

    lines.append("## Requirements")
    lines.append("")
    lines.append(
        "| Requirement | Title | Source | Architecture | Verification | Method | Status | Evidence |"
    )
    lines.append("| --- | --- | --- | --- | --- | --- | --- | --- |")
    for uid in sorted(model.requirements):
        requirement = model.requirements[uid]
        components = ", ".join(
            element.id for element in model.components if uid in element.requirements
        )
        cases = model.verifications_of(uid)
        case_ids = ", ".join(case.uid for case in cases)
        methods = ", ".join(
            dict.fromkeys(record.method for record in (model.evidence_of(case.uid) for case in cases) if record)
        )
        states = ", ".join(
            dict.fromkeys(record.status for record in (model.evidence_of(case.uid) for case in cases) if record)
        )
        artifacts = ", ".join(
            record.artifact or record.plan or ""
            for record in (model.evidence_of(case.uid) for case in cases)
            if record
        )
        lines.append(
            f"| {uid} | {requirement.header} | {requirement.ref} | {components} | "
            f"{case_ids} | {methods} | {states} | {artifacts} |"
        )
    lines.append("")

    lines.append("## Declared assumptions")
    lines.append("")
    lines.append("| Assumption | Title | Status |")
    lines.append("| --- | --- | --- |")
    for aid in sorted(model.assumptions):
        assumption = model.assumptions[aid]
        lines.append(f"| {assumption.id} | {assumption.title} | {assumption.status} |")
    lines.append("")
    return "\n".join(lines)


def _format_findings(findings: list[Finding]) -> str:
    return "\n".join(str(finding) for finding in findings)


def command_check(args: argparse.Namespace) -> int:
    """Validate the model and report the findings."""
    model = load_model(Path(args.root))
    findings = check_model(model, Path(args.root))
    errors = [finding for finding in findings if finding.severity == "error"]
    warnings = [finding for finding in findings if finding.severity == "warning"]
    if findings:
        print(_format_findings(findings))
    print(
        f"checked {len(model.requirements)} requirements, "
        f"{len(model.verifications)} verification cases, "
        f"{len(model.components)} components: "
        f"{len(errors)} errors, {len(warnings)} warnings"
    )
    return 1 if errors else 0


def command_report(args: argparse.Namespace) -> int:
    """Write the traceability matrix, or check that it is up to date."""
    root = Path(args.root)
    model = load_model(root)
    findings = check_model(model, root)
    errors = [finding for finding in findings if finding.severity == "error"]
    if errors:
        print(_format_findings(errors))
        print("the model has errors: the report was not written")
        return 1
    content = render_report(model)
    target = root / REPORT_PATH
    if args.check:
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current != content:
            print(f"{REPORT_PATH} is out of date: run python -m tools.traceability report")
            return 1
        print(f"{REPORT_PATH} is up to date")
        return 0
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    print(f"wrote {REPORT_PATH}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="tools.traceability", description=__doc__)
    parser.add_argument("--root", default=str(REPO_ROOT), help="repository root (default: the repo)")
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("check", help="validate the model, exit 1 on error")
    report = subparsers.add_parser("report", help="write the traceability matrix")
    report.add_argument("--check", action="store_true", help="fail if the report is out of date")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.command == "check":
        return command_check(args)
    return command_report(args)


if __name__ == "__main__":
    sys.exit(main())
